# Generated by Django 5.0.3 on 2024-05-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_alter_vendor_average_response_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='vendor',
            new_name='vendor_code',
        ),
    ]
