# Generated by Django 5.0.3 on 2024-05-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_rename_vendor_performance_vendor_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='vendor_code',
            new_name='vendor_name',
        ),
    ]
