# Generated by Django 5.0.4 on 2024-05-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0006_rename_vendor_name_performance_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quantityRating',
        ),
    ]
